$include:
- conf/lora/lora.yml
AudioDataset.duration: 1.0
AudioDataset.loudness_cutoff: -40.0
VampNet.embedding_dim: 1280
VampNet.n_codebooks: 14
VampNet.n_conditioning_codebooks: 4
VampNet.n_heads: 20
VampNet.n_layers: 16
fine_tune: true
fine_tune_checkpoint: ./runs/mac_smoke/domain_adapted/c2f/latest/vampnet/weights.pth
save_path: ./runs/mac_smoke/species_specific/c2f
train/AudioLoader.sources:
  - training_data/species_specific/train
val/AudioLoader.sources:
  - training_data/species_specific/val

num_iters: 1
batch_size: 4
num_workers: 6
amp: false

train/AudioDataset.n_examples: 4
val/AudioDataset.n_examples: 4

val_idx: [0]
val_freq: 1
sample_freq: 0
save_iters: []
