$include:
- conf/lora/lora.yml
fine_tune: true
fine_tune_checkpoint: ./runs/mac_smoke/domain_adapted/coarse/latest/vampnet/weights.pth
save_path: ./runs/mac_smoke/species_specific/coarse
train/AudioLoader.sources:
  - training_data/species_specific/train
val/AudioLoader.sources:
  - training_data/species_specific/val

AudioDataset.duration: 2.0

num_iters: 1
batch_size: 4
num_workers: 6
amp: false

train/AudioDataset.n_examples: 4
val/AudioDataset.n_examples: 4

val_idx: [0]
val_freq: 1
sample_freq: 0
save_iters: []